name: CI/CD Pipeline for MNIST Classification

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Train model
        run: |
          source venv/bin/activate
          python scripts/train_model.py

  build-docker:
    runs-on: ubuntu-latest
    needs: train-model
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t mnist-classifier .
          docker tag mnist-classifier your-dockerhub-username/mnist-classifier:latest
          docker push your-dockerhub-username/mnist-classifier:latest

  deploy-kubernetes:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yaml
